export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'https://plumbers-dubai.com'

export const SITE_NAME = 'SKS Plumbers'

export const DEFAULT_SEO = {
  title: 'SKS Plumbers Dubai | 24/7 Emergency Plumbing Services',
  description:
    'SKS Plumbers offers professional plumbing services in Dubai. Emergency plumber, water pump repair, drain cleaning, water heater services & more. Call 24/7.',
}

export const CATEGORY_SLUGS = [
  'commercial-plumbing',
  'emergency-plumbing',
  'general-plumbing-services',
  'pump-services',
  'residential-plumbing',
  'specialized-plumbing-services',
]

export const SERVICE_SLUGS = [
  '247-plumbing-service',
  'affordable-plumbing-service',
  'angle-valve-replacement',
  'apartment-plumbing-repair',
  'ariston-water-heater-repair',
  'automatic-pump-control-repair',
  'bathroom-plumbing',
  'blocked-drain-cleaning',
  'boiler-maintenance',
  'boiler-repair',
  'booster-and-pressure-pump-services',
  'booster-pump-repair',
  'broken-pipe-replacement',
  'chilled-water-pump-maintenance',
  'clogged-pipe-clearing',
  'commercial-plumbing',
  'commercial-pump-station-maintenance',
  'copper-pipe-repair',
  'dab-water-pump-repair',
  'davey-water-pump-repair',
  'dishwasher-plumbing-setup',
  'drain-unblocking-service',
  'emergency-pipe-burst-repair',
  'emergency-plumber',
  'fast-plumber-dubai',
  'faucet-installation',
  'faucet-repair',
  'float-switch-repair',
  'garden-plumbing-services',
  'grundfos-water-pump-repair',
  'hydro-jetting-service',
  'industrial-plumbing-services',
  'irrigation-pump-repair',
  'kitchen-plumbing-services',
  'leaking-water-heater-fix',
  'leaking-water-pump-repair',
  'licensed-plumber-dubai',
  'low-water-pressure-solutions',
  'main-water-line-repair',
  'milano-water-pump-repair',
  'noisy-water-pump-fix',
  'office-plumbing-services',
  'pedrollo-pump-repair',
  'pex-pipe-repair',
  'pipe-leak-repair',
  'pipe-repair-and-replacement',
  'plumbing-fixture-upgrades',
  'plumbing-repair',
  'pressure-pump-installation',
  'professional-plumbing-contractor',
  'pvc-pipe-repair',
  'residential-plumbing',
  'restaurant-plumbing-service',
  'rooter-service',
  'same-day-plumber',
  'sewage-and-sump-pump-services',
  'sewage-pump-maintenance',
  'shower-repair',
  'sink-repair',
  'slab-leak-repair',
  'stuart-turner-pump-repair',
  'submersible-pump-repair',
  'sump-pump-repair',
  'swimming-pool-pump-repair',
  'toilet-installation',
  'toilet-repair',
  'transfer-pump-repair',
  'villa-plumbing-maintenance',
  'washing-machine-plumbing-installation',
  'water-heater-installation',
  'water-heater-repair',
  'water-heater-services',
  'water-leak-detection',
  'water-pressure-regulator-replacement',
  'water-pump-installation',
  'water-pump-maintenance',
  'water-pump-motor-repair',
  'water-pump-pressure-switch-replacement',
  'water-pump-repair',
  'water-pump-replacement',
  'water-pump-services',
  'water-tank-cleaning',
  'water-tank-leak-repair',
  'water-tank-pump-repair',
  'wilo-pump-repair',
]

export const PAGE_SLUGS = ['about', 'contact']
